name: æŸ¥çœ‹ä»“åº“åå­—
on:
  workflow_dispatch: { }
jobs:
  activation:
    name: æŸ¥çœ‹ä»“åº“åå­— ğŸ”‘
    runs-on: ubuntu-latest
    steps:
      - name: æŸ¥çœ‹ä»“åº“åå­—
        run: |
          echo ${{github.event.repository.name}}